#version: "3.8"

x-spark-common: &spark-common
  image: apache/spark:3.5.1
  volumes:
    - ./jobs:/jobs
  networks:
    - spark-network

x-airflow-common: &airflow-common
  build:
    context: .
    dockerfile: Dockerfile
  env_file:
    - airflow.env  
  volumes:
    - ./jobs:/opt/airflow/jobs
    - ./dags:/opt/airflow/dags
    - ./logs:/opt/airflow/logs
    - ./plugins:/opt/airflow/plugins
  depends_on:
    - postgres  
  networks:
    - spark-network      

services:
  spark-master:
    <<: *spark-common
    container_name: spark-master
    command: >
      bash -c "
      /opt/spark/sbin/start-master.sh &&
      tail -f /opt/spark/logs/*"
    ports:
      - "7077:7077"
      - "9090:8080"

  spark-worker-1:
    <<: *spark-common
    container_name: spark-worker-1
    command: >
      bash -c "
      /opt/spark/sbin/start-worker.sh spark://spark-master:7077 &&
      tail -f /opt/spark/logs/*"
    depends_on:
      - spark-master
    environment:
      SPARK_MODE: worker
      SPARK_WORKER_CORES: 2
      SPARK_WORKER_MEMORY: 1g
      SPARK_MASTER_URL: spark://spark-master:7077  

  spark-worker-2:
    <<: *spark-common
    container_name: spark-worker-2
    command: >
      bash -c "
      /opt/spark/sbin/start-worker.sh spark://spark-master:7077 &&
      tail -f /opt/spark/logs/*"
    depends_on:
      - spark-master
    environment:
      SPARK_MODE: worker
      SPARK_WORKER_CORES: 2
      SPARK_WORKER_MEMORY: 1g
      SPARK_MASTER_URL: spark://spark-master:7077   

  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: airflow
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
    networks:
      - spark-network 

  scheduler:
    <<: *airflow-common
    container_name: airflow-scheduler
    command: >
      bash -c "airflow db migrate &&
         airflow users create --username amin --password amin --firstname dmin --lastname safout --role Admin --email aminsafoutali@gmeil.com &&
         airflow scheduler"  
  webserver:
    <<: *airflow-common
    container_name: airflow-webserver
    command: >
      bash -c "airflow db migrate && airflow webserver"
    ports:
      - "8080:8080"
    depends_on:
      - scheduler

  

networks:
  spark-network:
    driver: bridge
